### ISSUE TITLE
xm vision-based control

### ISSUE THREAD

**Issue by neverwinHao** [vegetabledogzy/baxter-teleoperation#1]
![5cfeebb51d23f2816e2f04e07f224e5](https://github.com/user-attachments/assets/1b442d27-d48d-4a98-821a-4581abcc8772)

**Comment by vegetabledogzy** [comment]
I should muzzle you

**Comment by neverwinHao** [comment]
> I should muzzle you

Trap your moth**！
![5cfeebb51d23f2816e2f04e07f224e5](https://github.com/user-attachments/assets/0c794d49-07e1-4a78-94da-506275b38313)
